security:
    hide_user_not_found:  false
    encoders:
        # This is the default user class returned from the LDAP provider below
        LdapTools\Bundle\LdapToolsBundle\Security\User\LdapUser: plaintext

    providers:
        ldap:
            id: ldap_tools.security.user.ldap_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # Use the default LDAP user provider defined above
            provider: ldap
            pattern: ^/
            logout: ~
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
        default:
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
           # form_login:
            #    login_path: app_login
            #    check_path: app_login
              #  csrf_token_generator: security.csrf.token_manager

        login:
            pattern: ^/
            anonymous: ~

    access_control:
       # - { path: ^/fournisseur/liste, roles: ROLE_USER }
        #- { path: ^/projet, roles: ROLE_USER }
        #- { path: ^/bilanmensuel, roles: ROLE_USER }
        #- { path: ^/listemodalites, roles: ROLE_USER }
        #- { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
