security:
    hide_user_not_found:  false
    encoders:
        LdapTools\Bundle\LdapToolsBundle\Security\User\LdapUser: plaintext
        App\Entity\User:
            algorithm: auto

    providers:
        chain_provider:
            chain:
                providers: [ user_db, ldap ]
        ldap:
            id: ldap_tools.security.user.ldap_user_provider
        user_db:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: chain_provider
            pattern: ^/
            logout: ~
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
       # default:
        #    guard:
         #       authenticators:
          #          - ldap_tools.security.ldap_guard_authenticator


        login:
            pattern: ^/
            anonymous: ~

    access_control:
        - { path: ^/fournisseur/liste, roles: ROLE_USER }
        - { path: ^/projet, roles: ROLE_USER }
        - { path: ^/bilanmensuel, roles: ROLE_USER }
        - { path: ^/listemodalites, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/pvinternes, role: ROLE_USER }
        - { path: ^/modalites, role: ROLE_USER }
        - { path: ^/export, role: ROLE_USER }
        - { path: ^/exporthome, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
