<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211103081824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE projet ADD debit1bm DOUBLE PRECISION DEFAULT NULL, ADD debit2bm DOUBLE PRECISION DEFAULT NULL, ADD debit3bm DOUBLE PRECISION DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE projet DROP debit1bm, DROP debit2bm, DROP debit3bm');
    }

    public function isTransactional(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

}
