<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211115131028 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pvinternes (id INT AUTO_INCREMENT NOT NULL, projet_id INT NOT NULL, isvalidate TINYINT(1) DEFAULT NULL, pourcentage DOUBLE PRECISION DEFAULT NULL, ismodified TINYINT(1) DEFAULT NULL, INDEX IDX_11CF5D2AC18272 (projet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE pvinternes ADD CONSTRAINT FK_11CF5D2AC18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE pvinternes');
    }
    public function isTransactional(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}
