<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211115131754 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pvinternes ADD date_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pvinternes ADD CONSTRAINT FK_11CF5D2AB897366B FOREIGN KEY (date_id) REFERENCES datepvinterne (id)');
        $this->addSql('CREATE INDEX IDX_11CF5D2AB897366B ON pvinternes (date_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pvinternes DROP FOREIGN KEY FK_11CF5D2AB897366B');
        $this->addSql('DROP INDEX IDX_11CF5D2AB897366B ON pvinternes');
        $this->addSql('ALTER TABLE pvinternes DROP date_id');
    }
    public function isTransactional(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
}
